# Generated by Django 3.0.5 on 2020-07-29 02:44

import PlannerApiApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlannerApiApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='current_total_team',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='point',
            name='current_total_user',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='team_total_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_total_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='point',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='dueDate',
            field=models.DateTimeField(default=PlannerApiApp.models.todayPlusWeek),
        ),
    ]
