# Generated by Django 3.0.5 on 2020-09-01 05:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PlannerApiApp', '0002_auto_20200728_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='pending_members',
            field=models.ManyToManyField(related_name='pending_teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
