# Generated by Django 3.0.5 on 2020-09-01 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlannerApiApp', '0003_team_pending_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='pending_members',
        ),
    ]
