# Generated by Django 3.0.5 on 2020-09-01 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlannerApiApp', '0005_joinrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JoinRequest',
        ),
    ]
