# Generated by Django 3.0.5 on 2021-01-09 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PlannerApiApp', '0006_delete_joinrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_pending_members',
            field=models.ManyToManyField(related_name='pending_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TeamRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL)),
                ('to_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_team', to='PlannerApiApp.Team')),
            ],
        ),
    ]
