# Generated by Django 3.0.5 on 2021-01-09 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlannerApiApp', '0007_auto_20210109_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_pending_members',
        ),
    ]
